name: Bundle for Deno
description: Create a Deno bundle for an npm package.
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  pkg:
    description: npm package name
    type: string

runs:
  using: node12
  main: index.js

branding:
  icon: send
  color: green