name: Create Bundles
description: Create bundles for a stdlib package.
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  target:
    description: Bundle target (`deno`, `umd`, or `esm`).
    type: string
  pkg:
    description: npm package name
    type: string

runs:
  using: node12
  main: index.js

branding:
  icon: send
  color: green